source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'INOPlaceholderTextView_Example', :exclusive => true do
  pod "INOPlaceholderTextView", :path => "../"
end

target 'INOPlaceholderTextView_Tests', :exclusive => true do
  pod "INOPlaceholderTextView", :path => "../"
end
